let question=[{
    'question':  'Which Indian startup has created it\'s own cryogenic engine?',
    'A': 'Bellatrix',
    'B': 'Godrej Aerospace',
    'C': 'Agnikul Cosmos',
    'D': 'Skyroot Aerospace',
},
{
    'question':  'What was the mascot of summer olympics 2020 called?',
    'A': 'Soohorang',
    'B': 'Miraitowa',
    'C': 'Vinicius',
    'D': 'Wenlock',
},
{
    'question':  'What is NAVIC?',
    'A': 'Remote sensing satellite to monitor ocean pollution',
    'B': 'Satellite communication system for Indian navy',
    'C': 'Satellite navigation system owned by the Indian Government',
    'D': 'Earth observation satellites to monitor crop weather, rainfall and crop yield',
},
{
    'question':  'Who won the first track and field gold medal for India in olympics?',
    'A': 'Neeraj Chopra',
    'B': 'P. T. Usha',
    'C': 'P. V. Sindhu',
    'D': 'Abhinav Bindra',
},
{
    'question':  'What is the name of India\'s first crypto unicorn?',
    'A': 'WazirX',
    'B': 'Coinbase',
    'C': 'Coinswitch Kuber',
    'D': 'CoinDCX ',
},
{
    'question':  'When is the earth day?',
    'A': '15th May',
    'B': '22nd April',
    'C': '21st May',
    'D': '5 June',
},
{
    'question':  'Who is the inventor of Ethereum?',
    'A': 'Satoshi Nakamoto',
    'B': 'Anatoly Yakovenko',
    'C': 'Vitalin Buterin',
    'D': 'W. Scott Stornetta',
},
{
    'question':  'Which country was the winner of FIFA 2018?',
    'A': 'Brazil',
    'B': 'Argentina',
    'C': 'Germany',
    'D': 'France',
},
{
    'question':  'What was India\'s first indegenously developed supercomputer?',
    'A': 'Param Shivaay',
    'B': 'Param 8000',
    'C': 'Cray XMP-14',
    'D': 'Pace',
},
{
    'question':  'What is the first bank in metaverse?',
    'A': 'Meta Defi',
    'B': 'JPMorgan',
    'C': 'Coindesk',
    'D': 'Decentracland bank',
},
{
    'question':  'Which country had the world\'s first stock market?',
    'A': 'U.S.A',
    'B': 'Belgium',
    'C': 'Netherlands',
    'D': 'Italy',
},
{
    'question':  'Which is asia\'s first stock exchange?',
    'A': 'National Stock Exchange.',
    'B': 'Bombay Stock Exchange.',
    'C': 'Shanghai stock Exchange',
    'D': 'Tokyo Stock Exchange',
},
{
    'question':  'What is the world\'s first horror film?',
    'A': 'The cave of the demons',
    'B': 'London after midnight',
    'C': 'The house of the devil',
    'D': 'The student of Prague',
},
{
    'question':  'Which Indian startup created a car running Matal air battery?',
    'A': 'Log9',
    'B': 'Ola',
    'C': 'Ather Energy',
    'D': 'Emflux motors',
},
{
    'question':  'Who was the first youtuber to cross 10 million subscribers in youtube?',
    'A': 'Pewdiepie',
    'B': 'Felix Kjellberg',
    'C': 'Smosh',
    'D': 'Mr. Beast',
}
]
module.exports = question