let question=[{
    'question':  'Which Indian startup has created it\'s own cryogenic engine?',
    'A': 'Bellatrix',
    'B': 'Godrej Aerospace',
    'C': 'Agnikul Cosmos',
    'D': 'Skyroot Aerospace',
},
{
    'question':  'What was the mascot of summer olympics 2020 called?',
    'A': 'Soohorang',
    'B': 'Miraitowa',
    'C': 'Vinicius',
    'D': 'Wenlock',
},
{
    'question':  'What is NAVIC?',
    'A': 'Remote sensing satellite to monitor ocean pollution',
    'B': 'Satellite communication system for Indian navy',
    'C': 'Satellite navigation system owned by the Indian Government',
    'D': 'Earth observation satellites to monitor crop weather, rainfall and crop yield',
},
{
    'question':  'Who won the first track and field gold medal for India in olympics?',
    'A': 'Neeraj Chopra',
    'B': 'P. T. Usha',
    'C': 'P. V. Sindhu',
    'D': 'Abhinav Bindra',
},
{
    'question':  'What is the name of India\'s first crypto unicorn?',
    'A': 'WazirX',
    'B': 'Coinbase',
    'C': 'Coinswitch Kuber',
    'D': 'CoinDCX ',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
}
]
module.exports = question