let question=[{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
},
{
    'question':  'Lorem ipsum dolor sit amet consectetur adipisicing elit?',
    'A': 'Lorem, ipsum dolor.',
    'B': 'Lorem, ipsum dolor.',
    'C': 'Lorem, ipsum dolor.',
    'D': 'Lorem, ipsum dolor.',
}
]
module.exports = question